Feature/generative pokemons list
tosqaaa/MyPokemons pull request #2
Opened 2024-06-18 19:19 UTC by tosqaaa

## Изменения
- Добавлена генерация карточек покемонов в main_activity
- Передача данных с main_acitvity в pokemon_detali_activity
- Оптимизация кода
- Улучшение способа хранения покемонов

# # Список покемонов (main_activity)
![main_activity](https://github.com/tosqaaa/MyPokemons/assets/123359559/5a74ebbf-5623-4a7a-bcca-d2b4da306caf)

## Детальная информация о покемоне (pokemon_detail_activity)
![detail_activity](https://github.com/tosqaaa/MyPokemons/assets/123359559/b13adacd-d68b-4537-b05a-305a0ad196e2)

2024-06-18 21:41 UTC, pzinkevich42innowise requested changes

2024-06-18 21:41 UTC, pzinkevich42innowise commented on app/src/main/java/com/example/mypokemons/MainActivity.kt
> +        for (pokemon in pokemonList.values) {
Может forEach ?

2024-06-18 21:41 UTC, pzinkevich42innowise commented on app/src/main/java/com/example/mypokemons/MainActivity.kt
> +        val rootView = binding.main
зачем в отдельную переменную?

2024-06-18 21:41 UTC, pzinkevich42innowise commented on app/src/main/java/com/example/mypokemons/MainActivity.kt
> +        val binding = PokemonCardBinding.inflate((inflater))
```suggestion
        val binding = PokemonCardBinding.inflate(LayoutInflater.from(this))
```

2024-06-18 21:41 UTC, pzinkevich42innowise commented on app/src/main/java/com/example/mypokemons/MainActivity.kt
> +                    setMargins(32, 16, 32, 16)
Перевод dp2px?

2024-06-18 21:41 UTC, pzinkevich42innowise commented on app/src/main/java/com/example/mypokemons/PokemonDetailActivity.kt
> +        //Toolbar setting
ну вот в отдельную функцию можно и вынести, чтобы не писать комментарий

2024-06-18 21:41 UTC, pzinkevich42innowise commented on app/src/main/java/com/example/mypokemons/PokemonDetailActivity.kt
>          val toolbar: Toolbar = findViewById(R.id.toolbar)
Через биндинг недоступен?

2024-06-18 21:41 UTC, pzinkevich42innowise commented on app/src/main/java/com/example/mypokemons/PokemonDetailActivity.kt
> +        //Getting id from main_activity
Аналогично.
Если хочется поделить блок кода комментариями - можно разделить его по функциям с говорящими именами

2024-06-18 21:41 UTC, pzinkevich42innowise commented on app/src/main/java/com/example/mypokemons/PokemonDetailActivity.kt
> +                image.setImageResource(poke?.imageRes?: R.drawable.bulbasaur)
Все покемоны без картинки - бульбазавры?

2024-06-18 21:41 UTC, pzinkevich42innowise commented on app/src/main/java/com/example/mypokemons/PokemonRepository.kt
> +            4312),
тут и далее стоит добавить именованые аргументы, не очень понятно какие данные в какие поля попадают7 Сделать быстро можно при помощи конеткстного меню по нажатию на лампочку

2024-06-18 21:41 UTC, pzinkevich42innowise commented on app/src/main/java/com/example/mypokemons/PokemonRepository.kt
> +    fun getPokemons(): Map<Int, Pokemon> = pokemons
Достаточно очевидные возвращаемые типы, можно не указывать

2024-06-18 21:41 UTC, pzinkevich42innowise commented on app/src/main/res/layout/pokemon_card.xml
> +        android:padding="8dp">
Обсуждали, что не самая хорошая идея плодить кучу ConstraintLayout на экране. Давай тут попробуем другой контейнер использовать

2024-06-18 21:41 UTC, pzinkevich42innowise commented on app/src/main/res/layout/pokemon_card.xml
> +            android:layout_height="120dp"
Не проверял на маленьком девайсе, но кажется жёсткие размеры вьюхи могут привести к тому, что она не поместится на экране

2024-06-19 17:54 UTC, tosqaaa commented on app/src/main/res/layout/pokemon_card.xml
Теперь список покемонов выглядит так:
![main_activity](https://github.com/tosqaaa/MyPokemons/assets/123359559/4a674fdf-2e3e-4f24-8a48-e562a0753540)

2024-06-19 19:57 UTC, pzinkevich42innowise requested changes

2024-06-19 19:57 UTC, pzinkevich42innowise commented on app/src/main/java/com/example/mypokemons/MainActivity.kt
> +    private fun dpToPx(dp: Int)= (dp * resources.displayMetrics.density).toInt()
Давай через TypedValue

2024-06-20 05:08 UTC, pzinkevich42innowise approved these changes

2024-06-20 08:03 UTC, merged